/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/catch-up`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/movies`; params?: Router.UnknownInputParams; } | { pathname: `/player`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/tv-guide`; params?: Router.UnknownInputParams; } | { pathname: `/tv-shows`; params?: Router.UnknownInputParams; } | { pathname: `/vod`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/movie/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/tv/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/catch-up`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/movies`; params?: Router.UnknownOutputParams; } | { pathname: `/player`; params?: Router.UnknownOutputParams; } | { pathname: `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/tv-guide`; params?: Router.UnknownOutputParams; } | { pathname: `/tv-shows`; params?: Router.UnknownOutputParams; } | { pathname: `/vod`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/movie/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/tv/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/catch-up${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/movies${`?${string}` | `#${string}` | ''}` | `/player${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/tv-guide${`?${string}` | `#${string}` | ''}` | `/tv-shows${`?${string}` | `#${string}` | ''}` | `/vod${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/catch-up`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/movies`; params?: Router.UnknownInputParams; } | { pathname: `/player`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/tv-guide`; params?: Router.UnknownInputParams; } | { pathname: `/tv-shows`; params?: Router.UnknownInputParams; } | { pathname: `/vod`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/movie/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/tv/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/movie/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/tv/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
